In [1]:
import pandas as pd

In [3]:
df = pd.read_excel("cancer patient data sets.xlsx")

In [4]:
df.head()

,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
0,P1,33,1,2,4,5,4,3,2,2,...,3,4,2,2,3,1,2,3,4,Low
1,P10,17,1,3,1,5,3,4,2,2,...,1,3,7,8,6,2,1,7,2,Medium
2,P100,35,1,4,5,6,5,5,4,6,...,8,7,9,2,1,4,6,7,2,High
3,P1000,37,1,7,7,7,7,6,7,7,...,4,2,3,1,4,5,6,7,5,High
4,P101,46,1,6,8,7,7,7,6,7,...,3,2,4,1,4,2,4,2,3,High

In [5]:
df.drop(['Patient Id'], axis=1, inplace=True)

In [6]:
df

,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,Obesity,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
0,33,1,2,4,5,4,3,2,2,4,...,3,4,2,2,3,1,2,3,4,Low
1,17,1,3,1,5,3,4,2,2,2,...,1,3,7,8,6,2,1,7,2,Medium
2,35,1,4,5,6,5,5,4,6,7,...,8,7,9,2,1,4,6,7,2,High
3,37,1,7,7,7,7,6,7,7,7,...,4,2,3,1,4,5,6,7,5,High
4,46,1,6,8,7,7,7,6,7,7,...,3,2,4,1,4,2,4,2,3,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,44,1,6,7,7,7,7,6,7,7,...,5,3,2,7,8,2,4,5,3,High
996,37,2,6,8,7,7,7,6,7,7,...,9,6,5,7,2,4,3,1,4,High
997,25,2,4,5,6,5,5,4,6,7,...,8,7,9,2,1,4,6,7,2,High
998,18,2,6,8,7,7,7,6,7,7,...,3,2,4,1,4,2,4,2,3,High
999,47,1,6,5,6,5,5,4,6,7,...,8,7,9,2,1,4,6,7,2,High

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1000 non-null   int64
 1   Gender                    1000 non-null   int64
 2   Air Pollution             1000 non-null   int64
 3   Alcohol use               1000 non-null   int64
 4   Dust Allergy              1000 non-null   int64
 5   OccuPational Hazards      1000 non-null   int64
 6   Genetic Risk              1000 non-null   int64
 7   chronic Lung Disease      1000 non-null   int64
 8   Balanced Diet             1000 non-null   int64
 9   Obesity                   1000 non-null   int64
 10  Smoking                   1000 non-null   int64
 11  Passive Smoker            1000 non-null   int64
 12  Chest Pain                1000 non-null   int64
 13  Coughing of Blood         1000 non-null   int64
 14  Fatigue                   1000 non-null   int64
 15  Weight Loss               1000 non-null   int64
 16  Shortness of Breath       1000 non-null   int64
 17  Wheezing                  1000 non-null   int64
 18  Swallowing Difficulty     1000 non-null   int64
 19  Clubbing of Finger Nails  1000 non-null   int64
 20  Frequent Cold             1000 non-null   int64
 21  Dry Cough                 1000 non-null   int64
 22  Snoring                   1000 non-null   int64
 23  Level                     1000 non-null   object
dtypes: int64(23), object(1)
memory usage: 187.6+ KB

In [8]:
df['Level'].unique()

array(['Low', 'Medium', 'High'], dtype=object)

In [9]:
target_dict = {'Low':1, 'Medium':2, 'High':3}

In [10]:
df['Level'] = df['Level'].map(target_dict)

In [24]:
df.shape

(1000, 24)

In [25]:
df = df.sample(750)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 750 entries, 524 to 301
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       750 non-null    int64
 1   Gender                    750 non-null    int64
 2   Air Pollution             750 non-null    int64
 3   Alcohol use               750 non-null    int64
 4   Dust Allergy              750 non-null    int64
 5   OccuPational Hazards      750 non-null    int64
 6   Genetic Risk              750 non-null    int64
 7   chronic Lung Disease      750 non-null    int64
 8   Balanced Diet             750 non-null    int64
 9   Obesity                   750 non-null    int64
 10  Smoking                   750 non-null    int64
 11  Passive Smoker            750 non-null    int64
 12  Chest Pain                750 non-null    int64
 13  Coughing of Blood         750 non-null    int64
 14  Fatigue                   750 non-null    int64
 15  Weight Loss               750 non-null    int64
 16  Shortness of Breath       750 non-null    int64
 17  Wheezing                  750 non-null    int64
 18  Swallowing Difficulty     750 non-null    int64
 19  Clubbing of Finger Nails  750 non-null    int64
 20  Frequent Cold             750 non-null    int64
 21  Dry Cough                 750 non-null    int64
 22  Snoring                   750 non-null    int64
 23  Level                     750 non-null    int64
dtypes: int64(24)
memory usage: 146.5 KB

### Building Classification model

In [27]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
model = RandomForestClassifier()

In [29]:
X = df.drop(['Level'], axis=1)
y = df['Level']

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=1)

### training the model

In [32]:
model.fit(X_train, y_train)

RandomForestClassifier()

In [33]:
preds = model.predict(X_test)

In [34]:
from sklearn.metrics import classification_report

In [35]:
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        29
           2       1.00      1.00      1.00        48
           3       1.00      1.00      1.00        36

    accuracy                           1.00       113
   macro avg       1.00      1.00      1.00       113
weighted avg       1.00      1.00      1.00       113